cursos/urls.py
from django.urls import path
from .views import home
from .views import cursos
from .views import contacto

urlpatterns = [
    path('', home, name='index'),
    path('cursos/', cursos, name='cursos'),
    path('contacto/', contacto, name='contacto'),
]

instituto_idiomas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('cursos.urls', 'cursos'))),
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cursos/models.py
from django.db import models

class Profesor(models.Model):
    dni = models.CharField('DNI', max_length=8, primary_key=True)
    apellido = models.CharField('Apellido', max_length=50, null=False, blank=False)
    nombre = models.CharField('Nombre', max_length=50, null=False, blank=False)
    fecha_nacimiento = models.DateField('Fecha de nacimiento')
    email = models.EmailField('Correo electrónico', null=False, blank=False)

    class Meta:
        verbose_name = 'Profesor'
        verbose_name_plural = 'Profesores'

    def __str__(self):
        return f'{self.nombre} {self.apellido}'

class Curso(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField('Titulo del curso', max_length=100, null=False, blank=False)
    idiomas = [
        ('I', 'Inglés'),
        ('A', 'Alemán'),
        ('F', 'Frances'),
        ('P', 'Portugués')
    ]
    idioma = models.CharField(max_length=1, choices=idiomas, default='I')
    niveles = [
        ('P', 'Principiante'),
        ('I', 'Intermedio'),
        ('A', 'Avanzado')
    ]
    nivel = models.CharField(max_length=1, choices=niveles, default='P')
    duracion = models.PositiveIntegerField('Duración (días)', default=30)
    modalidades = [
        ('P', 'Presencial'),
        ('V', 'Virtual')
    ]
    modalidad = models.CharField(max_length=1, choices=modalidades, default='P')
    profesor = models.ForeignKey(Profesor, null=False, blank=False, on_delete=models.CASCADE)
    inscripciones_abiertas = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

    def __str__(self):
        return f'{self.titulo}'


class Contacto(models.Model):
    id = models.AutoField(primary_key=True)
    asunto = models.CharField(max_length=50 ,null=False, blank=False)
    nombre = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=50, null=False, blank=False)
    mensaje = models.CharField(max_length=800, null=False, blank=False)
    info_enviada = models.BooleanField('Solicitud respondida', default=False)

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contactos'

    def __str__(self):
        return f'Mensaje de: {self.nombre} - {self.email}'

cursos/forms.py
from django import forms

class FormularioContacto(forms.Form):
    asunto = forms.CharField()
    nombre = forms.CharField()
    email = forms.EmailField()
    mensaje = forms.CharField(widget=forms.Textarea(attrs={'rows': 8, 'cols': 100}))

cursos/views.py
from django.shortcuts import render
from django.template import loader

from cursos.forms import FormularioContacto
from .models import Contacto, Curso, Profesor
from django.db.models import Q, query


def home(request):
    return render(request, 'index.html')


def cursos(request):
    cursos = Curso.objects.all()

    print(Profesor.objects.all())

    queryset = request.GET.get('buscar')

    if queryset:
        cursos = Curso.objects.filter(Q(titulo__icontains=queryset))

    idioma_seleccionado = request.GET.get('idioma')
    if idioma_seleccionado and idioma_seleccionado != 'Seleccionar...':
        cursos = cursos.filter(idioma=idioma_seleccionado)

    nivel_seleccionado = request.GET.get('nivel')
    if nivel_seleccionado and nivel_seleccionado != 'Seleccionar...':
        cursos = cursos.filter(nivel=nivel_seleccionado)

    print(cursos)

    return render(request, 'cursos.html', {'cursos': cursos})


def contacto(request):
    if request.method == 'POST':
        formulario_contacto = FormularioContacto(request.POST)
        if formulario_contacto.is_valid():
            info_formulario = formulario_contacto.cleaned_data
            datos_contacto = Contacto()

            datos_contacto.asunto = info_formulario['asunto']
            datos_contacto.nombre = info_formulario['nombre']
            datos_contacto.email = info_formulario['email']
            datos_contacto.mensaje = info_formulario['mensaje']
            datos_contacto.save()

            return render(request, 'mensaje_recibido.html', {'respuestasFormulario': info_formulario})
    else:
        formulario_contacto = FormularioContacto()
        return render(request, 'contacto.html', {'form': formulario_contacto})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#9CC254">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200;0,300;0,600;1,200;1,300&family=Mulish:ital,wght@0,200;0,300;1,200;1,300;1,600&family=Titillium+Web:ital,wght@0,200;0,300;0,600;1,200;1,300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0cebf067a0.js" crossorigin="anonymous"></script>
    <title>DinoTalk!</title>
    <link rel="shortcut icon" href="{% static 'images/dinotalk-icon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% block styles %} {% endblock styles %}">

</head>

<body>
    <header>
        <nav class="nav-bar">
            <a href="{% url 'cursos:index' %}" class="logo">DinoTalk!</a>
            <div class="menu-btn">
                <div class="menu-btn_burguer"></div>
            </div>
            <ul class="nav-menu">
                <li class="nav-menu-item"><a class="nav-menu-link" href="{% url 'cursos:index' %}">Inicio</a></li>
                <li class="nav-menu-item"><a class="nav-menu-link" href="{% url 'cursos:cursos' %}">Cursos</a></li>
                <li class="nav-menu-item"><a class="nav-menu-link" href="{% url 'cursos:contacto' %}">Contacto</a></li>
            </ul>
        </nav>
    </header>
    <main>
        {% block main %} {% endblock main %}
    </main>

    <footer>
        <img class="logo-footer" src="{% static 'images/dinotalk.png' %}" alt="logo-dinotalk">
        <div class="footer-contacto ">
            <div><i class="fas fa-envelope "></i>
                <a href="mailto:dinotalk@gmail.com">dinotalk@gmail.com</a>
            </div>
            <div>
                <i class="fas fa-phone "></i>
                <a href="tel:+541155555555">+54 9 11 5555 5555</a>
            </div>
        </div>
        <div id="firma">
            <p>Hecho con ❤️ by Solcii</p>
            <a href="https://github.com/Solcii"><i id="github" class="fab fa-github"></i></a>
            <a href="https://www.linkedin.com/in/sol-micaela-potschka-506713130/"><i id="linkedin" class="fab fa-linkedin"></i></a>
        </div>
    </footer>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/contacto.html
{% extends 'base.html' %} {% load static %}

<!-- Hoja de estilos de esta pagina -->
{% block styles %} {% static 'css/contacto.css' %} {% endblock styles %}

<!-- Contenido de esta pagina -->
{% block main %}
<div class="contenedor-form-datos">
    <section class="contenedor-formulario">
        <h1 class="titulo-contacto">Formulario de contacto</h1>
        {% if form.errors %}
        <p class="mensaje-error">Por favor revisa este campo</p>
        {% endif %}
        <form action="" method="POST" class="formulario-contacto">{% csrf_token %}
            <div class="contenedor-campos-formulario">
                {{ form.as_p }}
            </div>
            <input type="submit" value="Enviar" class="boton-formulario">
        </form>
    </section>
    <section class="contenedor-datos-contacto">
        <div class="datos-generales">
            <div class="datos-contacto">
                <i class="fas fa-envelope icono-contacto"></i>
                <p class="informacion-contacto">dinotalk@gmail.com</p>
            </div>
            <div class="datos-contacto">
                <i class="fas fa-phone icono-contacto"></i>
                <p>+54 9 11 5555 5555</p>
            </div>
            <p class="informacion-contacto frase-contacto">Seguinos en redes sociales para descubrir más sobre los cursos y conocer las novedades:</p>
            <div class="datos-contacto">
                <i class="fab fa-instagram icono-contacto"></i>
                <p class="informacion-contacto">@dinotalk_ok</p>
            </div>
            <div class="datos-contacto">
                <i class="fab fa-facebook icono-contacto"></i>
                <p class="informacion-contacto">DinoTalk Escuela de Idiomas (@dinotalk.idomas)</p>
            </div>
        </div>
    </section>
</div>
<section class="direccion">
    <p class="informacion-contacto frase-direccion">Encontranos en Sarmiento 1759, CABA</p>
    <iframe class="mapa" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3283.946964785964!2d-58.39379498477023!3d-34.605502580459046!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bccac3d4cec7e9%3A0x2df842ef71ea062a!2sSarmiento%201759%2C%20C1042%20ABG%2C%20Buenos%20Aires!5e0!3m2!1ses!2sar!4v1638977052732!5m2!1ses!2sar"
        width="1200" height="500" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</section>
{% endblock main %}

templates/cursos.html
{% extends 'base.html' %} {% load static %}

<!-- Hoja de estilos de esta pagina -->
{% block styles %} {% static 'css/cursos.css' %} {% endblock styles %}

<!-- Contenido de esta pagina -->


{% block main %}
<h1 class="titulo-seccion-cursos">Oferta de cursos</h1>

<div class="contenedor-barra-busqueda">
    <form method="get">
        <div id="custom-search-input">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar curso..." name="buscar" value="{{request.GET.buscar}}">
                <button type="submit" class="boton-buscar"><i class="fas fa-search lupa"></i><span class="texto-buscar">Buscar</span></button>
            </div>
        </div>
    </form>
    <div class="filtros">
        <i class="fas fa-filter icono-filtros"></i>
        <h2 class="titulo-filtros">Filtrar por</h2>
        <form class="filtros-form" method="get">
            <div class="selectores">
                <label for="idioma">Idioma:</label>
                <select name="idioma" id="idioma">
                <option>Seleccionar...</option>
                <option value="I">Inglés</option>
                <option value="A">Alemán</option>
                <option value="F">Francés</option>
                <option value="P">Portugués</option>
            </select>
            </div>
            <div class="selectores">
                <label for="nivel">Nivel:</label>
                <select name="nivel" id="nivel">
                <option>Seleccionar...</option>
                <option value="P">Principiante</option>
                <option value="I">Intermedio</option>
                <option value="A">Avanzado</option>
            </select>
            </div>
            <button type="submit" class="boton-filtros">Aplicar filtros</button>
        </form>
    </div>
</div>

<section class="oferta-cursos">
    {% if cursos %} {% for curso in cursos %}

    <div class="card-wrap">
        <div class="card-curso">
            <div class="card-front">
                {% if curso.idioma == 'I' %}
                <div class="card-curso-header ingles"></div>
                {% elif curso.idioma == 'A' %}
                <div class="card-curso-header aleman"></div>
                {% elif curso.idioma == 'F' %}
                <div class="card-curso-header frances"></div>
                {% else %}
                <div class="card-curso-header portugues"></div>
                {% endif %}
                <div class="card-curso-contenido">
                    <h2 class="titulo-curso">{{ curso.titulo }}</h2>
                    <h3 class="idioma">{{ curso.get_idioma_display }} {{ curso.get_nivel_display }} </h3>
                    <div class="footer-card-curso">
                        <div class="modalidad">
                            {% if curso.modalidad == 'V' %}
                            <i class="fas fa-desktop modalidad-icono"></i> {% else %}
                            <i class="fas fa-user-friends modalidad-icono"></i> {% endif %}
                            <h2 class="modalidad-titulo">{{ curso.get_modalidad_display }}</h2>
                        </div>
                        <div class="duracion">
                            <i class="far fa-calendar-alt duracion-icono"></i> {% if curso.duracion == 1 %}
                            <h2 class="duracion-titulo">{{ curso.duracion }} dia</h2>
                            {% else %}
                            <h2 class="duracion-titulo">{{ curso.duracion }} dias</h2>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-back">
                {% if curso.inscripciones_abiertas %}
                <h2 class="inscripciones inscripciones-abiertas">Incripciones abiertas</h2>
                {% else %}
                <h2 class="inscripciones incripciones-cerradas">Incripciones cerradas</h2>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %} {% else %}
    <h2 class="no-cursos">Lo sentimos, no tenemos cursos para mostrar en este momento...</h2>

    {% endif %}
</section>

{% endblock main %}

templates/index.html
{% extends 'base.html' %} {% load static %}

<!-- Hoja de estilos de esta pagina -->
{% block styles %} {% static 'css/index.css' %} {% endblock styles %}

<!-- Contenido de esta pagina -->
{% block main %}

<section class="explorar-idiomas">
    <h1 class="titulo-index">Descubre nuestra oferta de cursos</h1>
    <div class="grupo-cards-idiomas">
        <a class="card-idioma" href="cursos/?idioma=I&nivel=Seleccionar...">
            <img class="bandera-idioma" src="{% static 'images/flag-uk.png' %}" alt="Bandera UK">
            <h2 class="titulo-idioma">Inglés</h2>
        </a>
        <a class="card-idioma" href="cursos/?idioma=A&nivel=Seleccionar...">
            <img class="bandera-idioma" src="{% static 'images/germany-flag.png' %}" alt="Bandera Alemania">
            <h2 class="titulo-idioma">Alemán</h2>
        </a>
        <a class="card-idioma" href="cursos/?idioma=F&nivel=Seleccionar...">
            <img class="bandera-idioma" src="{% static 'images/french-flag.png' %}" alt="Bandera Francia">
            <h2 class="titulo-idioma">Francés</h2>
        </a>
        <a class="card-idioma" href="cursos/?idioma=P&nivel=Seleccionar...">
            <img class="bandera-idioma" src="{% static 'images/portugal-flag.png' %}" alt="Bandera Portugal">
            <h2 class="titulo-idioma">Portugués</h2>
        </a>
    </div>
</section>

<section class="quienes-somos">
    <h2 class="titulo-quienes-somos">¿Quiénes somos?</h2>
    <p class="texto-quienes-somos">Somos la primera Escuela de Idiomas pensada para personas de todas las edades, con una amplia oferta de cursos en cuatro idiomas: Inglés Británico, Alemán, Francés y Portugués (Portugal), en todos los niveles. Con profesores altamente capacitados
        y un método de enseñanza disruptivo, para que aprendas el lenguaje de manera natural, sin memorizar gramática, utilizando vocabulario y expresiones modernas nativas.
    </p>
</section>
<section class="informacion-general">
    <div class="info-card">
        <i class="fas fa-desktop"></i><span>/</span><i class="fas fa-user-friends"></i>
        <h2 class="info-titulo">Modalidad</h2>
        <p class="info-descripcion">Elije entre modalidad virtual o presencial, para que tu curso se adapte a tus necesidades y preferencias</p>
    </div>
    <div class="info-card">
        <i class="fas fa-comments"></i>
        <h2 class="info-titulo">Profesores nativos</h2>
        <p class="info-descripcion">Aprende con profesores nativos, utilizando lenguaje cotidiano y moderno para tu día a día</p>
    </div>
    <div class="info-card">
        <i class="fas fa-book-open"></i>
        <h2 class="info-titulo">Material extra</h2>
        <p class="info-descripcion">Todos nuestros cursos incluyen material extra para que continues practicando desde casa</p>
    </div>
    <div class="info-card">
        <i class="far fa-calendar-alt"></i>
        <h2 class="info-titulo">Todo el año</h2>
        <p class="info-descripcion">Con nuestra amplia oferta de cursos siempre tendrás una opción disponible para continuar aprendiendo </p>
    </div>
</section>

{% endblock main %}

templates/mensaje_recibido.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#9CC254">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200;0,300;0,600;1,200;1,300&family=Mulish:ital,wght@0,200;0,300;1,200;1,300;1,600&family=Titillium+Web:ital,wght@0,200;0,300;0,600;1,200;1,300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0cebf067a0.js" crossorigin="anonymous"></script>
    <title>DinoTalk!</title>
    <link rel="shortcut icon" href="{% static 'images/dinotalk-icon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/mensaje_recibido.css' %}">
</head>

<body>
    <div class="cuadro-mensaje">
        <img class="logo" src="{% static 'images/dinotalk.png' %}" alt="logo-dinotalk">
        <h1>Hemos recibido su mensaje correctamente <br> ¡en breve nos estaremos poniendo en contacto contigo!</h1>
        <a href="{% url 'cursos:index' %}">Volver al sitio</a>
</body>
</div>

</html>